# Generated by Django 6.0.4 on 2026-05-02 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('data', models.DateField(verbose_name='data')),
                ('periodo_da', models.DateField(verbose_name='periodo dal')),
                ('periodo_a', models.DateField(verbose_name='periodo al')),
                ('descrizione', models.CharField(max_length=300, verbose_name='descrizione')),
                ('snapshot', models.JSONField(help_text='Saldi per proprietario al momento della chiusura: {owner_id: saldo}', verbose_name='snapshot saldi')),
                ('note', models.TextField(blank=True, verbose_name='note')),
            ],
            options={
                'verbose_name': 'chiusura conti',
                'verbose_name_plural': 'chiusure conti',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='InterOwnerLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('data_apertura', models.DateField(verbose_name='data apertura')),
                ('importo_originale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='importo originale')),
                ('descrizione', models.CharField(max_length=300, verbose_name='descrizione')),
                ('chiuso', models.BooleanField(default=False, verbose_name='chiuso')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('owner_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestiti_ricevuti', to='properties.ownerprofile', verbose_name='proprietario debitore')),
                ('owner_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestiti_dati', to='properties.ownerprofile', verbose_name='proprietario prestante')),
            ],
            options={
                'verbose_name': 'prestito tra proprietari',
                'verbose_name_plural': 'prestiti tra proprietari',
                'ordering': ['-data_apertura'],
            },
        ),
        migrations.CreateModel(
            name='InterOwnerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('data', models.DateField(verbose_name='data')),
                ('importo', models.DecimalField(decimal_places=2, help_text='Positivo = owner_a deve a owner_da. Negativo = contrario.', max_digits=10, verbose_name='importo')),
                ('descrizione', models.CharField(max_length=300, verbose_name='descrizione')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('owner_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voci_bilaterali_ricevute', to='properties.ownerprofile', verbose_name='proprietario beneficiario')),
                ('owner_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voci_bilaterali_date', to='properties.ownerprofile', verbose_name='proprietario pagante')),
                ('riferimento_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inter_owner_entries', to='billing.expense', verbose_name='spesa collegata')),
                ('riferimento_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='accounting.interownerloan', verbose_name='prestito collegato')),
            ],
            options={
                'verbose_name': 'voce bilaterale tra proprietari',
                'verbose_name_plural': 'voci bilaterali tra proprietari',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='OwnerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('data', models.DateField(verbose_name='data')),
                ('descrizione', models.CharField(max_length=300, verbose_name='descrizione')),
                ('importo', models.DecimalField(decimal_places=2, help_text='Positivo = credito, negativo = debito.', max_digits=10, verbose_name='importo')),
                ('tipo', models.CharField(choices=[('incasso_affitto', 'Incasso affitto'), ('incasso_conguaglio', 'Incasso conguaglio'), ('spesa', 'Spesa'), ('distribuzione', 'Distribuzione utili'), ('aggiustamento', 'Aggiustamento')], max_length=30, verbose_name='tipo voce')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='properties.ownerprofile', verbose_name='proprietario')),
                ('riferimento_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.utilitycharge', verbose_name='conguaglio collegato')),
                ('riferimento_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.expense', verbose_name='spesa collegata')),
                ('riferimento_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.rentpayment', verbose_name='pagamento affitto collegato')),
            ],
            options={
                'verbose_name': 'voce partitario proprietario',
                'verbose_name_plural': 'voci partitario proprietari',
                'ordering': ['-data', 'owner__nominativo'],
            },
        ),
        migrations.CreateModel(
            name='WithholdingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('importo_mensile', models.DecimalField(decimal_places=2, help_text='Importo trattenuto ogni mese sulla distribuzione.', max_digits=10, verbose_name='importo mensile')),
                ('descrizione', models.CharField(max_length=300, verbose_name='descrizione')),
                ('attiva', models.BooleanField(default=True, verbose_name='attiva')),
                ('valid_from', models.DateField(verbose_name='valida dal')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='valida fino al')),
                ('owner_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trattenute_subite', to='properties.ownerprofile', verbose_name='chi riceve (subisce la trattenuta)')),
                ('owner_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trattenute_applicate', to='properties.ownerprofile', verbose_name='chi distribuisce (trattiene)')),
            ],
            options={
                'verbose_name': 'regola trattenuta',
                'verbose_name_plural': 'regole trattenute',
                'ordering': ['-valid_from'],
            },
        ),
    ]
