# Generated by Django 6.0.4 on 2026-05-03 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('billing', '0008_alter_utilitychargeline_charge_receivable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerledgerentry',
            name='riferimento_receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.receivable', verbose_name='addebito collegato'),
        ),
        migrations.AlterField(
            model_name='ownerledgerentry',
            name='riferimento_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.utilitycharge', verbose_name='conguaglio collegato (legacy)'),
        ),
        migrations.AlterField(
            model_name='ownerledgerentry',
            name='riferimento_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.rentpayment', verbose_name='pagamento affitto collegato (legacy)'),
        ),
    ]
