# Generated by Django 6.0.4 on 2026-05-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_ownerledgerentry_riferimento_receivable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerledgerentry',
            name='riferimento_charge',
        ),
        migrations.RemoveField(
            model_name='ownerledgerentry',
            name='riferimento_payment',
        ),
    ]
