# Generated by Django 6.0.4 on 2026-05-08 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_ownerledgerentry_riferimento_charge_and_more'),
        ('billing', '0016_expense_is_straordinaria'),
        ('properties', '0003_contract_nome_contract_termine'),
    ]

    operations = [
        migrations.AddField(
            model_name='interownerentry',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inter_owner_entries', to='billing.banktransaction', verbose_name='transazione bancaria collegata'),
        ),
        migrations.AddField(
            model_name='ownerledgerentry',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.banktransaction', verbose_name='transazione bancaria collegata'),
        ),
        migrations.AddField(
            model_name='ownerledgerentry',
            name='riferimento_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='accounting.ownersettlement', verbose_name='settlement collegato'),
        ),
        migrations.AlterField(
            model_name='ownerledgerentry',
            name='tipo',
            field=models.CharField(choices=[('incasso_affitto', 'Incasso affitto'), ('incasso_conguaglio', 'Incasso conguaglio'), ('spesa', 'Spesa'), ('anticipo', 'Anticipo (credito da spese di tasca)'), ('distribuzione', 'Distribuzione utili'), ('aggiustamento', 'Aggiustamento')], max_length=30, verbose_name='tipo voce'),
        ),
        migrations.AddConstraint(
            model_name='ownerledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('riferimento_receivable__isnull', False)), fields=('riferimento_receivable', 'owner', 'tipo'), name='uq_ledger_per_receivable_owner_tipo'),
        ),
        migrations.AddConstraint(
            model_name='ownerledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('riferimento_expense__isnull', False)), fields=('riferimento_expense', 'owner', 'tipo'), name='uq_ledger_per_expense_owner_tipo'),
        ),
    ]
