# Generated by Django 6.0.4 on 2026-05-09 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_interownerentry_bank_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interownerentry',
            name='riferimento_settlement',
            field=models.ForeignKey(blank=True, help_text='Settlement a cui questo movimento bilaterale è logicamente associato (utile quando la BT è di un anno successivo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inter_owner_entries', to='accounting.ownersettlement', verbose_name='settlement di competenza'),
        ),
    ]
