[uwsgi]

env = LC_ALL=it_IT.UTF-8
prj_dir = /code/
wsgi-file = %(prj_dir)/core/wsgi.py
pythonpath = /usr/local/lib/python3.13/site-packages
env = PYTHONPATH=%(prj_dir)/apps

# socket = /var/run/uwsgi/xylo.sock
# pidfile = /var/run/uwsgi/xylo.pid
socket-timeout = 200
buffer-size = 10000
processes = 2
threads = 1
#uid = www-data
#gid = www-data

http = :8000
master = true
http-keepalive = 1
lazy-apps = 1
wsgi-env-behavior = holy

req-logger = file:/var/log/uwsgi/access.log
logger = file:/var/log/uwsgi/errors.log
logdate = true
log-x-forwarded-for = true
#touch-logreopen = /var/log/uwsgi/touch-logrotate
chmod-socket    = 664

static-map = /static=/code/static
static-map = /media=/code/media
## dj collectstatics viene lanciato con --links per risparmiare spazio
## quindi uwsgi richiede che si dichiari che anche il target è sicuro
static-safe = /code/core/static
static-safe = /code/core/apps
static-safe = /usr/local/lib/
static-expires-uri = "/static/.*\.[a-f0-9]{12,}\.(css|js|png|jpg|jpeg|gif|ico|woff|ttf|otf|svg|scss|map|txt) 315360000"
