# Generated by Django 6.0.4 on 2026-05-02 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('codice', models.SlugField(help_text="Identificativo univoco del template (es. 'affitto_promemoria_pre').", unique=True, verbose_name='codice')),
                ('titolo', models.CharField(max_length=200, verbose_name='titolo')),
                ('corpo', models.TextField(help_text='Testo del messaggio con placeholder {{variabile}}.', verbose_name='corpo')),
                ('canale', models.CharField(choices=[('email', 'Email'), ('push', 'Push notification'), ('sms', 'SMS')], max_length=10, verbose_name='canale')),
            ],
            options={
                'verbose_name': 'template messaggio',
                'verbose_name_plural': 'template messaggi',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('endpoint', models.TextField(unique=True, verbose_name='endpoint')),
                ('p256dh', models.TextField(verbose_name='chiave p256dh')),
                ('auth', models.TextField(verbose_name='auth')),
                ('device_label', models.CharField(blank=True, max_length=100, verbose_name='etichetta device')),
                ('ultima_attivita', models.DateTimeField(blank=True, null=True, verbose_name='ultima attività')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='utente')),
            ],
            options={
                'verbose_name': 'iscrizione push',
                'verbose_name_plural': 'iscrizioni push',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('applicabile_a', models.CharField(choices=[('affitto', 'Affitto'), ('conguaglio', 'Conguaglio utenze'), ('extra', 'Addebito extra')], max_length=20, verbose_name='applicabile a')),
                ('giorni_offset', models.IntegerField(help_text='Giorni rispetto alla scadenza: negativo = prima, positivo = dopo.', verbose_name='giorni offset')),
                ('canale', models.CharField(choices=[('email', 'Solo email'), ('push', 'Solo push'), ('both', 'Email + push')], max_length=10, verbose_name='canale')),
                ('destinatario', models.CharField(choices=[('inquilino', 'Inquilino'), ('proprietario', 'Proprietario'), ('entrambi', 'Entrambi')], max_length=20, verbose_name='destinatario')),
                ('attiva', models.BooleanField(default=True, verbose_name='attiva')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_rules', to='notifications.messagetemplate', verbose_name='template messaggio')),
            ],
            options={
                'verbose_name': 'regola sollecito',
                'verbose_name_plural': 'regole solleciti',
                'ordering': ['applicabile_a', 'giorni_offset'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('oggetto', models.CharField(max_length=200, verbose_name='oggetto')),
                ('corpo', models.TextField(verbose_name='corpo')),
                ('inviata_at', models.DateTimeField(blank=True, null=True, verbose_name='inviata il')),
                ('letta_at', models.DateTimeField(blank=True, null=True, verbose_name='letta il')),
                ('canale', models.CharField(choices=[('email', 'Email'), ('push', 'Push notification'), ('sms', 'SMS')], max_length=10, verbose_name='canale')),
                ('oggetto_riferimento_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID oggetto collegato')),
                ('oggetto_riferimento_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='tipo oggetto collegato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='utente')),
                ('regola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.reminderrule', verbose_name='regola sollecito')),
            ],
            options={
                'verbose_name': 'notifica',
                'verbose_name_plural': 'notifiche',
                'ordering': ['-created_at'],
            },
        ),
    ]
