# Generated by Django 6.0.4 on 2026-05-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderrule',
            name='applicabile_a',
            field=models.CharField(choices=[('affitto', 'Affitto'), ('conguaglio', 'Utenze'), ('extra', 'Addebito extra')], max_length=20, verbose_name='applicabile a'),
        ),
    ]
