# Generated by Django 6.0.4 on 2026-08-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_messagetemplate_property_reminderrule_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='codice',
            field=models.SlugField(blank=True, help_text="Codice del messaggio (es. 'avviso_utenze', 'riepilogo_addebiti'): distingue comunicazioni diverse sullo stesso oggetto collegato.", verbose_name='tipo comunicazione'),
        ),
        migrations.AddField(
            model_name='notification',
            name='corpo_html',
            field=models.TextField(blank=True, help_text='Versione HTML realmente recapitata (vuota per push/SMS).', verbose_name='corpo HTML'),
        ),
        migrations.AddField(
            model_name='notification',
            name='destinatario',
            field=models.CharField(blank=True, help_text="Indirizzo o device a cui è stata spedita: può differire da user.email (email alternativa) e non è ricostruibile a posteriori se l'utente cambia recapito.", max_length=254, verbose_name='destinatario'),
        ),
        migrations.AddField(
            model_name='notification',
            name='errore',
            field=models.TextField(blank=True, help_text="Valorizzato se l'invio è fallito; in tal caso 'inviata il' resta vuoto.", verbose_name='errore'),
        ),
    ]
