# Generated by Django 6.0.4 on 2026-05-02 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualUtilityCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('voce', models.CharField(choices=[('tari', 'TARI (tassa rifiuti)'), ('altro', 'Altro')], default='tari', max_length=20, verbose_name='voce')),
                ('anno', models.PositiveSmallIntegerField(verbose_name='anno')),
                ('importo_annuale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='importo annuale')),
                ('valid_from', models.DateField(verbose_name='valido dal')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='valido fino al')),
                ('note', models.TextField(blank=True, verbose_name='note')),
            ],
            options={
                'verbose_name': 'costo utenza annuale',
                'verbose_name_plural': 'costi utenze annuali',
                'ordering': ['-anno', 'voce'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('codice', models.SlugField(unique=True, verbose_name='codice')),
                ('ripartibile_inquilini', models.BooleanField(default=False, verbose_name='ripartibile tra inquilini')),
            ],
            options={
                'verbose_name': 'categoria spesa',
                'verbose_name_plural': 'categorie spese',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('energia', 'Energia elettrica'), ('gas', 'Gas'), ('acqua', 'Acqua'), ('condominio', 'Condominio'), ('altro', 'Altro')], default='altro', max_length=20, verbose_name='tipo')),
                ('partita_iva', models.CharField(blank=True, max_length=20, verbose_name='partita IVA')),
                ('contatto', models.TextField(blank=True, verbose_name='contatto')),
            ],
            options={
                'verbose_name': 'fornitore',
                'verbose_name_plural': 'fornitori',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UtilityChargePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('periodo_da', models.DateField(verbose_name='periodo dal')),
                ('periodo_a', models.DateField(verbose_name='periodo al')),
                ('criterio_ripartizione', models.CharField(choices=[('a_testa', 'A testa (uguale per tutti)'), ('per_stanza', 'Per stanza'), ('pro_rata_giorni', 'Pro-rata giorni di presenza')], default='pro_rata_giorni', max_length=20, verbose_name='criterio ripartizione')),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('inviato', 'Inviato')], default='bozza', max_length=20, verbose_name='stato')),
                ('manual_totals', models.JSONField(blank=True, help_text='JSON per import storico: {inquilino_id: importo_totale}', null=True, verbose_name='totali manuali')),
                ('data_invio', models.DateField(blank=True, null=True, verbose_name='data invio')),
                ('note', models.TextField(blank=True, verbose_name='note')),
            ],
            options={
                'verbose_name': 'periodo conguaglio utenze',
                'verbose_name_plural': 'periodi conguaglio utenze',
                'ordering': ['-periodo_da'],
            },
        ),
        migrations.CreateModel(
            name='ExtraCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('data', models.DateField(verbose_name='data')),
                ('descrizione', models.CharField(max_length=300, verbose_name='descrizione')),
                ('importo', models.DecimalField(decimal_places=2, help_text='Positivo per addebito, negativo per accredito/rimborso.', max_digits=10, verbose_name='importo')),
                ('scadenza', models.DateField(verbose_name='scadenza')),
                ('stato', models.CharField(choices=[('atteso', 'Atteso'), ('dichiarato', 'Dichiarato (da confermare)'), ('pagato', 'Pagato'), ('in_ritardo', 'In ritardo'), ('insoluto', 'Insoluto')], default='atteso', max_length=20, verbose_name='stato')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_charges', to='properties.roomassignment', verbose_name='assegnazione')),
            ],
            options={
                'verbose_name': 'addebito extra',
                'verbose_name_plural': 'addebiti extra',
                'ordering': ['-scadenza'],
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('competenza_da', models.DateField(verbose_name='competenza dal')),
                ('competenza_a', models.DateField(verbose_name='competenza al')),
                ('importo_dovuto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='importo dovuto')),
                ('importo_pagato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='importo pagato')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data pagamento')),
                ('scadenza', models.DateField(verbose_name='scadenza')),
                ('stato', models.CharField(choices=[('atteso', 'Atteso'), ('dichiarato', 'Dichiarato (da confermare)'), ('pagato', 'Pagato'), ('in_ritardo', 'In ritardo'), ('insoluto', 'Insoluto')], default='atteso', max_length=20, verbose_name='stato')),
                ('is_aggiustamento', models.BooleanField(default=False, help_text='Pagamento pro-rata per ingresso/uscita a metà mese.', verbose_name='è aggiustamento')),
                ('ricevuta', models.FileField(blank=True, null=True, upload_to='ricevute/affitti/', verbose_name='ricevuta')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_payments', to='properties.roomassignment', verbose_name='assegnazione')),
                ('bank_account_destinazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rent_payments', to='properties.ownerbankaccount', verbose_name='conto destinazione')),
                ('incassato_da_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incassi_affitto', to='properties.ownerprofile', verbose_name='incassato da proprietario')),
            ],
            options={
                'verbose_name': 'pagamento affitto',
                'verbose_name_plural': 'pagamenti affitto',
                'ordering': ['-scadenza', 'assignment__tenant__nominativo'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('data', models.DateField(verbose_name='data')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='importo')),
                ('descrizione', models.CharField(max_length=300, verbose_name='descrizione')),
                ('ripartibile_su_inquilini', models.BooleanField(default=False, verbose_name='ripartibile su inquilini')),
                ('allegato', models.FileField(blank=True, null=True, upload_to='spese/', verbose_name='allegato')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('anticipata_da_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spese_anticipate', to='properties.ownerprofile', verbose_name='anticipata da proprietario')),
                ('riferimento_quota_owner', models.ForeignKey(blank=True, help_text='Es. Bruna paga IMU di Fabio: questo campo vale Fabio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spese_per_quota', to='properties.ownerprofile', verbose_name='riferimento quota proprietario')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='billing.expensecategory', verbose_name='categoria')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='billing.supplier', verbose_name='fornitore')),
            ],
            options={
                'verbose_name': 'spesa',
                'verbose_name_plural': 'spese',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('numero_fattura', models.CharField(blank=True, max_length=100, verbose_name='numero fattura')),
                ('data_emissione', models.DateField(verbose_name='data emissione')),
                ('periodo_da', models.DateField(verbose_name='periodo dal')),
                ('periodo_a', models.DateField(verbose_name='periodo al')),
                ('importo_totale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='importo totale')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='bollette/', verbose_name='file PDF')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('pagata_da_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bollette_pagate', to='properties.ownerprofile', verbose_name='pagata da proprietario')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utility_bills', to='billing.supplier', verbose_name='fornitore')),
            ],
            options={
                'verbose_name': 'bolletta utenza',
                'verbose_name_plural': 'bollette utenze',
                'ordering': ['-data_emissione'],
            },
        ),
        migrations.CreateModel(
            name='UtilityCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('importo_totale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='importo totale')),
                ('scadenza', models.DateField(verbose_name='scadenza')),
                ('stato', models.CharField(choices=[('atteso', 'Atteso'), ('dichiarato', 'Dichiarato (da confermare)'), ('pagato', 'Pagato'), ('in_ritardo', 'In ritardo'), ('insoluto', 'Insoluto')], default='atteso', max_length=20, verbose_name='stato')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data pagamento')),
                ('importo_pagato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='importo pagato')),
                ('ricevuta', models.FileField(blank=True, null=True, upload_to='ricevute/conguagli/', verbose_name='ricevuta')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utility_charges', to='properties.roomassignment', verbose_name='assegnazione')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='billing.utilitychargeperiod', verbose_name='periodo')),
            ],
            options={
                'verbose_name': 'conguaglio utenze inquilino',
                'verbose_name_plural': 'conguagli utenze inquilini',
                'ordering': ['-period__periodo_da', 'assignment__tenant__nominativo'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('data', models.DateField(verbose_name='data')),
                ('descrizione', models.TextField(verbose_name='descrizione')),
                ('importo', models.DecimalField(decimal_places=2, help_text='Positivo = entrata, negativo = uscita.', max_digits=10, verbose_name='importo')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('owner_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='properties.ownerbankaccount', verbose_name='conto proprietario')),
                ('riconciliato_con_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='billing.rentpayment', verbose_name='riconciliato con pagamento affitto')),
                ('riconciliato_con_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='billing.utilitycharge', verbose_name='riconciliato con conguaglio')),
            ],
            options={
                'verbose_name': 'transazione bancaria',
                'verbose_name_plural': 'transazioni bancarie',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='UtilityChargeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('voce', models.CharField(choices=[('luce', 'Luce'), ('gas', 'Gas'), ('tari', 'TARI'), ('altro', 'Altro')], max_length=20, verbose_name='voce')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='importo')),
                ('dettaglio', models.TextField(blank=True, help_text="Testo esplicativo per la PWA inquilino (es. 'quota pro-rata 15 giorni su 30').", verbose_name='dettaglio')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.utilitycharge', verbose_name='conguaglio')),
            ],
            options={
                'verbose_name': 'riga conguaglio',
                'verbose_name_plural': 'righe conguaglio',
                'ordering': ['voce'],
            },
        ),
        migrations.AddConstraint(
            model_name='utilitycharge',
            constraint=models.UniqueConstraint(fields=('period', 'assignment'), name='utility_charge_unique_period_assignment'),
        ),
    ]
