# Generated by Django 6.0.4 on 2026-05-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracharge',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='data pagamento'),
        ),
        migrations.AddField(
            model_name='extracharge',
            name='importo_pagato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='importo pagato'),
        ),
    ]
