# Generated by Django 6.0.4 on 2026-05-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_extracharge_data_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCondominioRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('valid_from', models.DateField(verbose_name='valido dal')),
                ('valid_to', models.DateField(blank=True, help_text="Lasciare vuoto se la quota e' tuttora in vigore.", null=True, verbose_name='valido fino al')),
                ('importo_mensile', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='importo mensile (€)')),
                ('note', models.TextField(blank=True, verbose_name='note')),
            ],
            options={
                'verbose_name': 'quota condominiale inquilini',
                'verbose_name_plural': 'quote condominiali inquilini',
                'ordering': ['-valid_from'],
            },
        ),
    ]
