# Generated by Django 6.0.4 on 2026-05-02 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_tenantcondominiorate_contract'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcondominiorate',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_condominio_inquilini', to='properties.contract', verbose_name='contratto'),
        ),
    ]
