# Generated by Django 6.0.4 on 2026-05-03 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_tenantcondominiorate_contract_notnull'),
        ('properties', '0002_contract_default_pagatore_bollette'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracharge',
            name='bank_account_destinazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extra_charges', to='properties.ownerbankaccount', verbose_name='conto destinazione'),
        ),
        migrations.AddField(
            model_name='extracharge',
            name='incassato_da_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incassi_extra', to='properties.ownerprofile', verbose_name='incassato da proprietario'),
        ),
        migrations.AddField(
            model_name='utilitycharge',
            name='bank_account_destinazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utility_charges', to='properties.ownerbankaccount', verbose_name='conto destinazione'),
        ),
        migrations.AddField(
            model_name='utilitycharge',
            name='incassato_da_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incassi_utility', to='properties.ownerprofile', verbose_name='incassato da proprietario'),
        ),
    ]
