# Generated by Django 6.0.4 on 2026-05-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_extracharge_bank_account_destinazione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitybill',
            name='consumo',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='kWh per la luce, m³ per gas e acqua.', max_digits=10, null=True, verbose_name='consumo'),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='prodotto',
            field=models.CharField(choices=[('luce', 'Luce (kWh)'), ('gas', 'Gas (m³)'), ('acqua', 'Acqua (m³)')], default='luce', max_length=10, verbose_name='prodotto'),
        ),
    ]
