# Generated by Django 6.0.4 on 2026-05-03 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_utilitybill_consumo_utilitybill_prodotto'),
        ('properties', '0003_contract_nome_contract_termine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitychargeline',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.utilitycharge', verbose_name='conguaglio (legacy)'),
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('causale', models.CharField(choices=[('affitto', 'Affitto'), ('utenze', 'Utenze'), ('extra', 'Extra')], max_length=10, verbose_name='causale')),
                ('descrizione', models.CharField(blank=True, help_text='Valorizzata per causale=extra; opzionale altrove.', max_length=300, verbose_name='descrizione')),
                ('competenza_da', models.DateField(verbose_name='competenza dal')),
                ('competenza_a', models.DateField(blank=True, help_text='Nullo per causale=extra (addebito puntuale).', null=True, verbose_name='competenza al')),
                ('scadenza', models.DateField(verbose_name='scadenza')),
                ('importo_dovuto', models.DecimalField(decimal_places=2, help_text='Per causale=extra può essere negativo (rimborso/accredito).', max_digits=10, verbose_name='importo dovuto')),
                ('stato', models.CharField(choices=[('atteso', 'Atteso'), ('dichiarato', 'Dichiarato (da confermare)'), ('pagato', 'Pagato'), ('in_ritardo', 'In ritardo'), ('insoluto', 'Insoluto')], default='atteso', max_length=20, verbose_name='stato')),
                ('importo_pagato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='importo pagato')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data pagamento')),
                ('ricevuta', models.FileField(blank=True, null=True, upload_to='ricevute/', verbose_name='ricevuta')),
                ('is_aggiustamento', models.BooleanField(default=False, help_text='Pro-rata di ingresso/uscita (rilevante per causale=affitto).', verbose_name='è aggiustamento')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='properties.roomassignment', verbose_name='assegnazione')),
                ('bank_account_destinazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='properties.ownerbankaccount', verbose_name='conto destinazione')),
                ('incassato_da_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incassi', to='properties.ownerprofile', verbose_name='incassato da proprietario')),
                ('utility_period', models.ForeignKey(blank=True, help_text='Valorizzato per causale=utenze.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='billing.utilitychargeperiod', verbose_name='periodo conguaglio')),
            ],
            options={
                'verbose_name': 'addebito inquilino',
                'verbose_name_plural': 'addebiti inquilini',
                'ordering': ['-scadenza', 'assignment__tenant__nominativo'],
            },
        ),
        migrations.CreateModel(
            name='BankTransactionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('importo', models.DecimalField(decimal_places=2, help_text='Quota della transazione imputata a questo addebito.', max_digits=10, verbose_name='importo allocato')),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.banktransaction', verbose_name='transazione')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.receivable', verbose_name='addebito')),
            ],
            options={
                'verbose_name': 'allocazione transazione',
                'verbose_name_plural': 'allocazioni transazioni',
            },
        ),
        migrations.AddField(
            model_name='utilitychargeline',
            name='receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utility_lines', to='billing.receivable', verbose_name='addebito'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['causale', 'stato'], name='billing_rec_causale_e1189e_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['assignment', 'causale'], name='billing_rec_assignm_504f8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='receivable',
            constraint=models.UniqueConstraint(condition=models.Q(('causale', 'affitto')), fields=('assignment', 'competenza_da', 'competenza_a'), name='receivable_affitto_unique'),
        ),
        migrations.AddConstraint(
            model_name='receivable',
            constraint=models.UniqueConstraint(condition=models.Q(('causale', 'utenze')), fields=('utility_period', 'assignment'), name='receivable_utenze_unique'),
        ),
        migrations.AddConstraint(
            model_name='banktransactionallocation',
            constraint=models.UniqueConstraint(fields=('bank_transaction', 'receivable'), name='allocation_unique_pair'),
        ),
    ]
