# Generated by Django 6.0.4 on 2026-05-03 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_ownerledgerentry_riferimento_charge_and_more'),
        ('billing', '0009_popola_receivable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracharge',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='extracharge',
            name='bank_account_destinazione',
        ),
        migrations.RemoveField(
            model_name='extracharge',
            name='incassato_da_owner',
        ),
        migrations.RemoveField(
            model_name='rentpayment',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='rentpayment',
            name='bank_account_destinazione',
        ),
        migrations.RemoveField(
            model_name='rentpayment',
            name='incassato_da_owner',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='riconciliato_con_payment',
        ),
        migrations.RemoveConstraint(
            model_name='utilitycharge',
            name='utility_charge_unique_period_assignment',
        ),
        migrations.RemoveField(
            model_name='utilitychargeline',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='riconciliato_con_charge',
        ),
        migrations.AlterField(
            model_name='utilitychargeline',
            name='receivable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_lines', to='billing.receivable', verbose_name='addebito'),
        ),
        migrations.DeleteModel(
            name='ExtraCharge',
        ),
        migrations.DeleteModel(
            name='RentPayment',
        ),
        migrations.DeleteModel(
            name='UtilityCharge',
        ),
    ]
