# Generated by Django 6.0.4 on 2026-05-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_remove_extracharge_assignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantcondominiorate',
            options={'ordering': ['-valid_from'], 'verbose_name': 'quota spese condominiali', 'verbose_name_plural': 'quote spese condominiali'},
        ),
    ]
