# Generated by Django 6.0.4 on 2026-05-03 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_tenantcondominiorate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilitychargeline',
            options={'ordering': ['voce'], 'verbose_name': 'riga utenze', 'verbose_name_plural': 'righe utenze'},
        ),
        migrations.AlterModelOptions(
            name='utilitychargeperiod',
            options={'ordering': ['-periodo_da'], 'verbose_name': 'periodo utenze', 'verbose_name_plural': 'periodi utenze'},
        ),
        migrations.AlterField(
            model_name='receivable',
            name='utility_period',
            field=models.ForeignKey(blank=True, help_text='Valorizzato per causale=utenze.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='billing.utilitychargeperiod', verbose_name='periodo utenze'),
        ),
    ]
