# Generated by Django 6.0.4 on 2026-05-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_wipe_utenze_legacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilitychargeperiod',
            name='manual_totals',
        ),
        migrations.AddField(
            model_name='receivable',
            name='giorni_presenza',
            field=models.PositiveIntegerField(blank=True, help_text='Numeratore della ripartizione utenze (giorni nel periodo).', null=True, verbose_name='giorni di presenza'),
        ),
        migrations.AddField(
            model_name='utilitychargeperiod',
            name='annual_utility_costs',
            field=models.ManyToManyField(blank=True, help_text='Costi annuali (TARI) che concorrono al totale TARI. Popolato a mano.', related_name='periods', to='billing.annualutilitycost', verbose_name='costi annuali agganciati'),
        ),
        migrations.AddField(
            model_name='utilitychargeperiod',
            name='giorni_totali',
            field=models.PositiveIntegerField(default=0, help_text='Somma dei giorni di presenza di tutti gli inquilini (denominatore della ripartizione).', verbose_name='giorni-persona totali'),
        ),
        migrations.AddField(
            model_name='utilitychargeperiod',
            name='nota_calcolo',
            field=models.TextField(blank=True, verbose_name='nota calcolo'),
        ),
        migrations.AddField(
            model_name='utilitychargeperiod',
            name='tot_altro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='totale altro'),
        ),
        migrations.AddField(
            model_name='utilitychargeperiod',
            name='tot_gas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='totale gas'),
        ),
        migrations.AddField(
            model_name='utilitychargeperiod',
            name='tot_luce',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='totale luce'),
        ),
        migrations.AddField(
            model_name='utilitychargeperiod',
            name='tot_tari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='totale TARI'),
        ),
        migrations.AddField(
            model_name='utilitychargeperiod',
            name='utility_bills',
            field=models.ManyToManyField(blank=True, help_text='Bollette fornitore che concorrono ai totali luce/gas. Popolato a mano.', related_name='periods', to='billing.utilitybill', verbose_name='bollette agganciate'),
        ),
        migrations.DeleteModel(
            name='UtilityChargeLine',
        ),
    ]
