# Generated by Django 6.0.4 on 2026-05-06 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_utenze_trasparenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitybill',
            name='expense',
            field=models.OneToOneField(blank=True, editable=False, help_text="Expense generata automaticamente quando la bolletta ha 'pagata da proprietario' valorizzato.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_bill', to='billing.expense', verbose_name='spesa collegata'),
        ),
    ]
