# Generated by Django 6.0.4 on 2026-05-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_utilitybill_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_straordinaria',
            field=models.BooleanField(default=False, help_text='Spese straordinarie (es. rifacimento bagno) vengono raggruppate separatamente al settlement annuale.', verbose_name='straordinaria'),
        ),
    ]
