# Generated by Django 6.0.4 on 2026-05-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_expense_is_straordinaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivable',
            name='causale',
            field=models.CharField(choices=[('affitto', 'Affitto'), ('utenze', 'Utenze'), ('extra', 'Extra'), ('caparra', 'Caparra')], max_length=10, verbose_name='causale'),
        ),
    ]
