# Generated by Django 6.0.4 on 2026-05-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_receivable_causale_caparra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivable',
            name='causale',
            field=models.CharField(choices=[('affitto', 'Affitto'), ('utenze', 'Utenze'), ('extra', 'Extra'), ('caparra', 'Caparra'), ('registrazione', 'Registrazione contratto')], max_length=15, verbose_name='causale'),
        ),
    ]
