# Generated by Django 6.0.4 on 2026-05-16 15:13

from django.db import migrations, models


def caparra_to_deposito(apps, schema_editor):
    Receivable = apps.get_model("billing", "Receivable")
    Receivable.objects.filter(causale="caparra").update(causale="deposito")


def deposito_to_caparra(apps, schema_editor):
    Receivable = apps.get_model("billing", "Receivable")
    Receivable.objects.filter(causale="deposito").update(causale="caparra")


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_alter_receivable_causale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivable',
            name='causale',
            field=models.CharField(choices=[('affitto', 'Affitto'), ('utenze', 'Utenze'), ('extra', 'Extra'), ('deposito', 'Deposito'), ('registrazione', 'Registrazione contratto')], max_length=15, verbose_name='causale'),
        ),
        migrations.RunPython(caparra_to_deposito, deposito_to_caparra),
    ]
