# Generated by Django 6.0.4 on 2026-05-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_rinomina_deposito_natura_materasso'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitychargeperiod',
            name='avvisi_inviati_at',
            field=models.DateTimeField(blank=True, help_text="Data/ora dell'ultimo invio reale degli avvisi agli inquilini.", null=True, verbose_name='avvisi inviati il'),
        ),
    ]
