# Generated by Django 6.0.4 on 2026-06-03 09:46

import billing.models.utilities
import django.db.models.deletion
from django.db import migrations, models


def popola_immobile(apps, schema_editor):
    """Assegna le bollette esistenti all'unico immobile (mono-immobile attuale)."""
    UtilityBill = apps.get_model("billing", "UtilityBill")
    Property = apps.get_model("properties", "Property")
    immobile = Property.objects.order_by("pk").first()
    if immobile:
        UtilityBill.objects.filter(immobile__isnull=True).update(immobile=immobile)


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_utilitychargeperiod_avvisi_inviati_at'),
        ('properties', '0011_seed_property_e_conto_utenze'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitybill',
            name='immobile',
            field=models.ForeignKey(blank=True, help_text='Immobile a cui appartiene la bolletta (organizza i PDF su disco).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utility_bills', to='properties.property', verbose_name='immobile'),
        ),
        migrations.RunPython(popola_immobile, reverse_noop),
        migrations.AlterField(
            model_name='utilitybill',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, upload_to=billing.models.utilities.utility_bill_upload_to, verbose_name='file PDF'),
        ),
    ]
