# Generated by Django 6.0.4 on 2026-07-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_annualutilitycost_property_expense_property_and_more'),
        ('properties', '0014_alter_ownershipshare_options_contract_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcondominiorate',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text="Vuoto = quota base dell'immobile; valorizzato = eccezione valida solo per questo inquilino.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_condominio', to='properties.tenantprofile', verbose_name='inquilino'),
        ),
    ]
