# Generated by Django 6.0.4 on 2026-07-29 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_tenantcondominiorate_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivableComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('testo', models.TextField(verbose_name='testo')),
                ('autore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commenti_addebiti', to=settings.AUTH_USER_MODEL, verbose_name='autore')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='billing.receivable', verbose_name='addebito')),
            ],
            options={
                'verbose_name': 'commento addebito',
                'verbose_name_plural': 'commenti addebiti',
                'ordering': ['created_at'],
            },
        ),
    ]
