# Generated by Django 6.0.4 on 2026-07-30 11:09

import billing.models.utilities
import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_receivablecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='allegato',
            field=models.FileField(blank=True, null=True, storage=core.storages.media_private_storage, upload_to='spese/', verbose_name='allegato'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='ricevuta',
            field=models.FileField(blank=True, null=True, storage=core.storages.media_private_storage, upload_to='ricevute/', verbose_name='ricevuta'),
        ),
        migrations.AlterField(
            model_name='utilitybill',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, storage=core.storages.media_private_storage, upload_to=billing.models.utilities.utility_bill_upload_to, verbose_name='file PDF'),
        ),
    ]
