# Generated by Django 6.0.4 on 2026-08-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_tenantcondominiorate_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitybill',
            name='motivo_esclusione',
            field=models.CharField(blank=True, help_text="Es. 'Canone RAI', 'Costi di allaccio'.", max_length=200, verbose_name='motivo esclusione'),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='quota_esclusa',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Parte dell'importo NON ripartita sugli inquilini, a carico della proprietà (es. canone RAI, aumento potenza, allaccio).", max_digits=10, verbose_name='quota esclusa'),
        ),
    ]
