# Generated by Django 6.0.4 on 2026-08-06 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_utilitybill_motivo_esclusione_and_more'),
        ('properties', '0033_toglie_atto_subentro_utenze'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyUtilityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('voce', models.CharField(choices=[('luce', 'Luce'), ('gas', 'Gas'), ('acqua', 'Acqua'), ('tari', 'TARI')], max_length=20, verbose_name='voce')),
                ('gestione', models.CharField(choices=[('proprieta', 'Gestita dalla proprietà'), ('inquilino', "A carico dell'inquilino")], default='proprieta', max_length=20, verbose_name='gestione')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_services', to='properties.property', verbose_name='immobile')),
            ],
            options={
                'verbose_name': 'utenza della casa',
                'verbose_name_plural': 'utenze della casa',
                'ordering': ['property', 'voce'],
                'constraints': [models.UniqueConstraint(fields=('property', 'voce'), name='property_utility_service_unique_per_voce')],
            },
        ),
    ]
