# Generated by Django 6.0.4 on 2026-08-25 00:01
"""Vincolo: un addebito pagato deve dire chi ha incassato.

ATTENZIONE prima del deploy: se esistono Receivable `pagato` senza
`incassato_da_owner` questa migration fallisce con IntegrityError. Sanarli
PRIMA con::

    uv run manage.py sana_incassi_senza_incassante            # dry-run
    uv run manage.py sana_incassi_senza_incassante --apply
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_seed_property_utility_services'),
        ('properties', '0036_ownerbankaccount_properties'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='receivable',
            constraint=models.CheckConstraint(condition=models.Q(('incassato_da_owner__isnull', True), ('stato', 'pagato'), _negated=True), name='receivable_pagato_ha_incassante', violation_error_message='Un addebito pagato deve indicare il proprietario che ha incassato.'),
        ),
    ]
