# Generated by Django 6.0.4 on 2026-08-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_receivable_receivable_pagato_ha_incassante'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitychargeperiod',
            name='motivo_esclusione_tari',
            field=models.CharField(blank=True, help_text="Es. 'Stanza singola sfitta'.", max_length=200, verbose_name='motivo esclusione TARI'),
        ),
        migrations.AddField(
            model_name='utilitychargeperiod',
            name='quota_esclusa_tari',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Parte della TARI del periodo NON ripartita sugli inquilini, a carico della proprietà (es. la quota dei posti sfitti, che non va scaricata su chi c'è).", max_digits=10, verbose_name='quota TARI esclusa'),
        ),
    ]
