# Generated by Django 6.0.4 on 2026-09-03 11:37

import core.storages
import django.core.validators
import properties.models.tenant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_utilitychargeperiod_motivo_esclusione_tari_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='allegato',
            field=models.FileField(blank=True, help_text='Fattura o ricevuta: PDF o immagine (JPG/PNG), massimo 10 MB.', null=True, storage=core.storages.media_private_storage, upload_to='spese/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), properties.models.tenant.valida_dimensione_documento], verbose_name='allegato'),
        ),
    ]
