# Generated by Django 6.0.4 on 2026-05-02 00:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('data_stipula', models.DateField(verbose_name='data stipula')),
                ('data_decorrenza', models.DateField(verbose_name='data decorrenza')),
                ('durata_anni', models.PositiveSmallIntegerField(verbose_name='durata (anni)')),
                ('asseverato', models.BooleanField(default=False, verbose_name='asseverato')),
                ('regime_fiscale', models.CharField(choices=[('cedolare_10', 'Cedolare secca 10%'), ('cedolare_21', 'Cedolare secca 21%'), ('irpef', 'IRPEF ordinario')], default='cedolare_10', max_length=20, verbose_name='regime fiscale')),
                ('note', models.TextField(blank=True, verbose_name='note')),
            ],
            options={
                'verbose_name': 'contratto',
                'verbose_name_plural': 'contratti',
                'ordering': ['-data_decorrenza'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('superficie_mq', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='superficie (mq)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='foto')),
                ('ordinamento', models.PositiveSmallIntegerField(default=0, verbose_name='ordinamento')),
            ],
            options={
                'verbose_name': 'stanza',
                'verbose_name_plural': 'stanze',
                'ordering': ['ordinamento', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('nominativo', models.CharField(max_length=200, verbose_name='nominativo')),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, verbose_name='codice fiscale')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owner_profile', to=settings.AUTH_USER_MODEL, verbose_name='utente')),
            ],
            options={
                'verbose_name': 'profilo proprietario',
                'verbose_name_plural': 'profili proprietari',
                'ordering': ['nominativo'],
            },
        ),
        migrations.CreateModel(
            name='OwnerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('banca', models.CharField(max_length=100, verbose_name='banca')),
                ('intestatario', models.CharField(max_length=200, verbose_name='intestatario')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('attivo', models.BooleanField(default=True, verbose_name='attivo')),
                ('ordinamento', models.PositiveSmallIntegerField(default=0, verbose_name='ordinamento')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='properties.ownerprofile', verbose_name='proprietario')),
            ],
            options={
                'verbose_name': 'conto bancario proprietario',
                'verbose_name_plural': 'conti bancari proprietari',
                'ordering': ['owner__nominativo', 'ordinamento', 'banca'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('valid_from', models.DateField(verbose_name='valida dal')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='valida fino al')),
                ('quota', models.DecimalField(decimal_places=4, help_text='Es. 0.3333 per un terzo. La somma delle quote attive in ogni data deve fare 1.0.', max_digits=5, verbose_name='quota (0-1)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_shares', to='properties.ownerprofile', verbose_name='proprietario')),
            ],
            options={
                'verbose_name': 'quota di proprietà',
                'verbose_name_plural': 'quote di proprietà',
                'ordering': ['-valid_from', 'owner__nominativo'],
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('nominativo', models.CharField(max_length=200, verbose_name='nominativo')),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, verbose_name='codice fiscale')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('email_alt', models.EmailField(blank=True, max_length=254, verbose_name='email alternativa')),
                ('giorno_pagamento_affitto', models.PositiveSmallIntegerField(help_text="Giorno del mese in cui l'inquilino paga (1-28).", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='giorno pagamento affitto')),
                ('frequenza_conguagli', models.CharField(choices=[('mensile', 'Mensile'), ('bimestrale', 'Bimestrale')], default='mensile', max_length=20, verbose_name='frequenza conguagli')),
                ('note_pagamento', models.TextField(blank=True, verbose_name='note pagamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_profile', to=settings.AUTH_USER_MODEL, verbose_name='utente')),
            ],
            options={
                'verbose_name': 'profilo inquilino',
                'verbose_name_plural': 'profili inquilini',
                'ordering': ['nominativo'],
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('valid_from', models.DateField(verbose_name='inizio occupazione')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='fine occupazione')),
                ('canone_mensile', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='canone mensile')),
                ('deposito_versato', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='deposito versato')),
                ('deposito_restituito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='deposito restituito')),
                ('data_restituzione_deposito', models.DateField(blank=True, null=True, verbose_name='data restituzione deposito')),
                ('data_atto_cessione', models.DateField(blank=True, help_text="Valorizzato se l'occupazione è iniziata con una cessione registrata.", null=True, verbose_name='data atto cessione')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='properties.room', verbose_name='stanza')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='properties.tenantprofile', verbose_name='inquilino')),
            ],
            options={
                'verbose_name': 'assegnazione stanza',
                'verbose_name_plural': 'assegnazioni stanze',
                'ordering': ['-valid_from', 'room__nome'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='room_assignment_valid_to_after_valid_from')],
            },
        ),
    ]
