# Generated by Django 6.0.4 on 2026-05-02 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='default_pagatore_bollette',
            field=models.ForeignKey(blank=True, help_text='Proprietario che, per convenzione, anticipa il pagamento delle bollette luce/gas verso i fornitori.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratti_pagatore_bollette', to='properties.ownerprofile', verbose_name='paga le bollette utenze'),
        ),
    ]
