# Generated by Django 6.0.4 on 2026-05-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_contract_default_pagatore_bollette'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='nome',
            field=models.CharField(blank=True, help_text="Nome identificativo (es. 'Contratto 2023', 'Contratto 2025').", max_length=100, verbose_name='nome'),
        ),
        migrations.AddField(
            model_name='contract',
            name='termine',
            field=models.DateField(blank=True, help_text='Data effettiva di chiusura del contratto (uscita anticipata). Diversa dalla scadenza naturale = data_decorrenza + durata_anni.', null=True, verbose_name='termine'),
        ),
    ]
