# Generated by Django 6.0.4 on 2026-05-10 23:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_contract_nome_contract_termine'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='data_restituzione_deposito',
            field=models.DateField(blank=True, null=True, verbose_name='data restituzione deposito'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='data_versamento_deposito',
            field=models.DateField(blank=True, null=True, verbose_name='data versamento deposito'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='deposito_restituito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='deposito restituito'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='deposito_versato',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Caparra versata dall'inquilino. Vale per l'intero rapporto, anche se l'inquilino cambia stanza o contratto.", max_digits=10, verbose_name='deposito versato'),
        ),
    ]
