# Generated by Django 6.0.4 on 2026-05-10 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_caparra_assignment_to_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomassignment',
            name='data_restituzione_deposito',
        ),
        migrations.RemoveField(
            model_name='roomassignment',
            name='deposito_restituito',
        ),
        migrations.RemoveField(
            model_name='roomassignment',
            name='deposito_versato',
        ),
    ]
