# Generated by Django 6.0.4 on 2026-05-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_caparra_from_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='ciclo_fatturazione',
            field=models.CharField(choices=[('solare', 'Mese solare (1-31)'), ('ingresso', 'Dal giorno di ingresso')], default='solare', help_text="Solare: mese di calendario (1-31), con pro-rata su ingresso/uscita infra-mese. Ingresso: mensilità dal giorno di valid_from al giorno precedente del mese successivo (es. 9/2-8/3), canone pieno tranne moncone finale all'uscita.", max_length=20, verbose_name='ciclo fatturazione affitto'),
        ),
    ]
