# Generated by Django 6.0.4 on 2026-05-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_tenant_ciclo_fatturazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomassignment',
            name='costo_cessione',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Costo TOTALE della registrazione/cessione del contratto. Se valorizzato, alla data di inizio occupazione genera: il 50% come addebito all'inquilino entrante (Receivable 'registrazione') e il 50% come spesa proprietari ripartita pro-quota. Lasciare vuoto per il contratto collettivo (nessun addebito).", max_digits=10, null=True, verbose_name='costo cessione (totale)'),
        ),
    ]
