# Generated by Django 6.0.4 on 2026-05-31 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_rinomina_campi_restituzione_deposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomassignment',
            name='bank_account_affitto',
            field=models.ForeignKey(blank=True, help_text="Override: conto su cui versare l'affitto di questa assegnazione. Se vuoto, si usa il conto della proprietà.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_affitto', to='properties.ownerbankaccount', verbose_name='conto incasso affitto'),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('indirizzo', models.CharField(blank=True, max_length=255, verbose_name='indirizzo')),
                ('bank_account_utenze', models.ForeignKey(blank=True, help_text='Conto su cui gli inquilini versano le utenze/conguagli di questo immobile.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties_utenze', to='properties.ownerbankaccount', verbose_name='conto domiciliazione utenze')),
            ],
            options={
                'verbose_name': 'immobile',
                'verbose_name_plural': 'immobili',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='properties.property', verbose_name='immobile'),
        ),
    ]
