# Generated by Django 6.0.4 on 2026-06-03 20:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_seed_property_e_conto_utenze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='deposito_versato',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Deposito versato dall'inquilino. Vale per l'intero rapporto, anche se l'inquilino cambia stanza o contratto.", max_digits=10, verbose_name='deposito versato'),
        ),
    ]
