# Generated by Django 6.0.4 on 2026-06-09 12:02

import django.core.validators
import django.db.models.deletion
import properties.models.tenant
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_tenantprofile_deposito_versato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('tipo', models.CharField(choices=[('carta_identita', "Carta d'identità"), ('codice_fiscale', 'Codice fiscale / Tessera sanitaria'), ('passaporto', 'Passaporto'), ('permesso_soggiorno', 'Permesso di soggiorno'), ('contratto_lavoro', 'Contratto di lavoro'), ('altro', 'Altro')], default='altro', max_length=30, verbose_name='tipo documento')),
                ('file', models.FileField(help_text='PDF o immagine (JPG/PNG), massimo 10 MB.', upload_to=properties.models.tenant.tenant_document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), properties.models.tenant.valida_dimensione_documento], verbose_name='file')),
                ('descrizione', models.CharField(blank=True, help_text="Facoltativa: es. 'fronte', 'retro', o dettaglio per 'Altro'.", max_length=200, verbose_name='descrizione')),
                ('data_scadenza', models.DateField(blank=True, help_text="Facoltativa: utile per carta d'identità, passaporto, permesso di soggiorno.", null=True, verbose_name='data di scadenza')),
                ('caricato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_inquilini_caricati', to=settings.AUTH_USER_MODEL, verbose_name='caricato da')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='properties.tenantprofile', verbose_name='inquilino')),
            ],
            options={
                'verbose_name': 'documento inquilino',
                'verbose_name_plural': 'documenti inquilini',
                'ordering': ['tenant__nominativo', 'tipo', '-created_at'],
            },
        ),
    ]
