# Generated by Django 6.0.4 on 2026-07-14 19:19

import django.core.validators
import django.db.models.deletion
import properties.models.property
import properties.models.tenant
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_tenantdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='foto_hero',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.property.galleria_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), properties.models.tenant.valida_dimensione_documento], verbose_name='foto principale (hero)'),
        ),
        migrations.AddField(
            model_name='property',
            name='foto_mappa',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.property.galleria_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), properties.models.tenant.valida_dimensione_documento], verbose_name='screenshot mappa'),
        ),
        migrations.AddField(
            model_name='property',
            name='foto_planimetria',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.property.galleria_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), properties.models.tenant.valida_dimensione_documento], verbose_name='planimetria'),
        ),
        migrations.AddField(
            model_name='property',
            name='pubblica',
            field=models.BooleanField(default=False, help_text='Se attiva, la galleria è raggiungibile pubblicamente senza login.', verbose_name='galleria pubblica'),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, help_text="Identificativo per l'URL pubblico della galleria (/g/<slug>). Se vuoto viene generato dal nome.", max_length=140, null=True, unique=True, verbose_name='slug pubblico'),
        ),
        migrations.AddField(
            model_name='property',
            name='testi_pubblici',
            field=models.JSONField(blank=True, default=dict, help_text='Testi liberi editabili della pagina pubblica (hero, facts, posizione). Le chiavi mancanti usano i fallback del frontend.', verbose_name='testi pubblici'),
        ),
        migrations.AddField(
            model_name='room',
            name='colore',
            field=models.CharField(blank=True, help_text="Colore del pallino/legenda in galleria (es. 'var(--vp-terra)' o '#c96f4a').", max_length=40, verbose_name='colore identificativo'),
        ),
        migrations.AddField(
            model_name='room',
            name='descrizione',
            field=models.TextField(blank=True, help_text="Descrizione breve della stanza mostrata nell'annuncio.", verbose_name='descrizione'),
        ),
        migrations.AddField(
            model_name='room',
            name='disponibile',
            field=models.BooleanField(default=True, help_text="Se disattiva: badge 'Non disponibile' e nessuna foto in galleria.", verbose_name='disponibile (annuncio)'),
        ),
        migrations.AddField(
            model_name='room',
            name='libera_dal',
            field=models.DateField(blank=True, help_text='Data indicativa da cui la stanza è disponibile (facoltativa).', null=True, verbose_name='libera dal'),
        ),
        migrations.AddField(
            model_name='room',
            name='prezzo_mensile',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prezzo d'annuncio, distinto dal canone effettivo delle assegnazioni.", max_digits=10, null=True, verbose_name='prezzo mensile (annuncio)'),
        ),
        migrations.AddField(
            model_name='room',
            name='pubblica',
            field=models.BooleanField(default=True, verbose_name='mostra in galleria'),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('image', models.ImageField(upload_to=properties.models.property.galleria_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), properties.models.tenant.valida_dimensione_documento], verbose_name='immagine')),
                ('didascalia', models.CharField(blank=True, max_length=200, verbose_name='didascalia')),
                ('ordinamento', models.PositiveSmallIntegerField(default=0, verbose_name='ordinamento')),
                ('caricato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images_caricate', to=settings.AUTH_USER_MODEL, verbose_name='caricato da')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='properties.property', verbose_name='immobile')),
                ('room', models.ForeignKey(blank=True, help_text="Se vuoto, foto di uno spazio comune dell'immobile.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='properties.room', verbose_name='stanza')),
            ],
            options={
                'verbose_name': 'foto galleria',
                'verbose_name_plural': 'foto galleria',
                'ordering': ['room__ordinamento', 'ordinamento', 'id'],
            },
        ),
    ]
