# Generated by Django 6.0.4 on 2026-07-14 19:19

from django.db import migrations
from django.utils.text import slugify


def backfill_slug(apps, schema_editor):
    Property = apps.get_model("properties", "Property")
    visti = set()
    for prop in Property.objects.filter(slug__isnull=True).order_by("pk"):
        base = slugify(prop.nome) or "immobile"
        slug = base
        n = 2
        while slug in visti or Property.objects.exclude(pk=prop.pk).filter(slug=slug).exists():
            slug = f"{base}-{n}"
            n += 1
        prop.slug = slug
        visti.add(slug)
        prop.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_property_foto_hero_property_foto_mappa_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_slug, migrations.RunPython.noop),
    ]
