# Generated by Django 6.0.4 on 2026-07-14 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_backfill_property_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['room__ordinamento', 'area__ordinamento', 'ordinamento', 'id'], 'verbose_name': 'foto galleria', 'verbose_name_plural': 'foto galleria'},
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='room',
            field=models.ForeignKey(blank=True, help_text="Camera (oggetto d'affitto) ritratta dalla foto.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='properties.room', verbose_name='camera'),
        ),
        migrations.CreateModel(
            name='GalleryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('colore', models.CharField(blank=True, max_length=40, verbose_name='colore identificativo')),
                ('descrizione', models.TextField(blank=True, verbose_name='descrizione')),
                ('ordinamento', models.PositiveSmallIntegerField(default=0, verbose_name='ordinamento')),
                ('pubblica', models.BooleanField(default=True, verbose_name='mostra in galleria')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_areas', to='properties.property', verbose_name='immobile')),
            ],
            options={
                'verbose_name': 'ambiente comune',
                'verbose_name_plural': 'ambienti comuni',
                'ordering': ['ordinamento', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Ambiente comune (cucina, soggiorno, bagni…) ritratto dalla foto.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='properties.galleryarea', verbose_name='ambiente comune'),
        ),
    ]
