# Generated by Django 6.0.4 on 2026-07-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_alter_galleryimage_options_alter_galleryimage_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='formato',
            field=models.CharField(choices=[('quadrato', 'Quadrato'), ('orizzontale', 'Orizzontale'), ('verticale', 'Verticale')], default='quadrato', help_text='Forma del riquadro in galleria: quadrato, orizzontale o verticale.', max_length=12, verbose_name='formato riquadro'),
        ),
    ]
