# Generated by Django 6.0.4 on 2026-07-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_alter_ownershipshare_options_contract_property_and_more'),
        ('properties', '0017_galleryimage_formato'),
    ]

    operations = [
    ]
