# Generated by Django 6.0.4 on 2026-07-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_merge_20260723_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tipo_gestione',
            field=models.CharField(choices=[('stanze', 'A stanze'), ('unita_intera', 'Unità intera')], default='stanze', max_length=20, verbose_name='tipo di gestione'),
        ),
    ]
