# Generated by Django 6.0.4 on 2026-07-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_property_tipo_gestione'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ownershipshare',
            constraint=models.UniqueConstraint(fields=('property', 'owner', 'valid_from'), name='uniq_quota_owner_periodo'),
        ),
    ]
