# Generated by Django 6.0.4 on 2026-07-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_ownershipshare_uniq_quota_owner_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdocument',
            name='tipo',
            field=models.CharField(choices=[('carta_identita', "Carta d'identità"), ('codice_fiscale', 'Codice fiscale / Tessera sanitaria'), ('passaporto', 'Passaporto'), ('permesso_soggiorno', 'Permesso di soggiorno'), ('contratto_lavoro', 'Contratto di lavoro'), ('ricevuta_subentro', 'Ricevuta del subentro'), ('atto_subentro', 'Atto di subentro'), ('altro', 'Altro')], default='altro', max_length=30, verbose_name='tipo documento'),
        ),
    ]
