# Generated by Django 6.0.4 on 2026-07-29 20:48

import django.core.validators
import django.db.models.deletion
import properties.models.property
import properties.models.tenant
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_alter_tenantdocument_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('tipo', models.CharField(choices=[('contratto', 'Contratto di locazione'), ('side_letter', 'Side letter'), ('registrazione_contratto', 'Registrazione contratto'), ('regolamento_condominiale', 'Regolamento condominiale'), ('altro', 'Altro')], default='altro', max_length=30, verbose_name='tipo documento')),
                ('file', models.FileField(help_text='PDF o immagine (JPG/PNG), massimo 10 MB.', upload_to=properties.models.property.property_document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), properties.models.tenant.valida_dimensione_documento], verbose_name='file')),
                ('descrizione', models.CharField(blank=True, help_text='Facoltativa: dettaglio del documento (es. anno, versione).', max_length=200, verbose_name='descrizione')),
                ('data_scadenza', models.DateField(blank=True, help_text='Facoltativa: es. scadenza registrazione da rinnovare.', null=True, verbose_name='data di scadenza')),
                ('caricato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_proprieta_caricati', to=settings.AUTH_USER_MODEL, verbose_name='caricato da')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='properties.property', verbose_name='immobile')),
            ],
            options={
                'verbose_name': 'documento immobile',
                'verbose_name_plural': 'documenti immobile',
                'ordering': ['property__nome', 'tipo', '-created_at'],
            },
        ),
    ]
