# Generated by Django 6.0.4 on 2026-07-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_propertydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocument',
            name='visibile_inquilini',
            field=models.BooleanField(default=False, help_text="Se attivo, gli inquilini dell'immobile vedono e scaricano il documento nella loro area (es. contratto, regolamento condominiale).", verbose_name='visibile agli inquilini'),
        ),
    ]
