# Generated by Django 6.0.4 on 2026-07-30 11:09

import core.storages
import django.core.validators
import properties.models.property
import properties.models.tenant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_propertydocument_visibile_inquilini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='file',
            field=models.FileField(help_text='PDF o immagine (JPG/PNG), massimo 10 MB.', storage=core.storages.media_private_storage, upload_to=properties.models.property.property_document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), properties.models.tenant.valida_dimensione_documento], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='tenantdocument',
            name='file',
            field=models.FileField(help_text='PDF o immagine (JPG/PNG), massimo 10 MB.', storage=core.storages.media_private_storage, upload_to=properties.models.tenant.tenant_document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), properties.models.tenant.valida_dimensione_documento], verbose_name='file'),
        ),
    ]
