# Generated by Django 6.0.4 on 2026-08-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_alter_propertydocument_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdocument',
            name='tipo',
            field=models.CharField(choices=[('carta_identita', "Carta d'identità"), ('codice_fiscale', 'Codice fiscale / Tessera sanitaria'), ('passaporto', 'Passaporto'), ('permesso_soggiorno', 'Permesso di soggiorno'), ('contratto_lavoro', 'Contratto di lavoro'), ('ricevuta_registrazione', 'Ricevuta di registrazione (agenzia)'), ('ricevuta_subentro', 'Ricevuta del subentro'), ('atto_subentro', 'Atto di subentro'), ('altro', 'Altro')], default='altro', max_length=30, verbose_name='tipo documento'),
        ),
    ]
