# Generated by Django 6.0.4 on 2026-08-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_alter_tenantdocument_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='cittadinanza',
            field=models.CharField(blank=True, max_length=60, verbose_name='cittadinanza'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='cognome',
            field=models.CharField(blank=True, help_text='Separato dal nome perché i moduli ufficiali hanno due caselle distinte.', max_length=100, verbose_name='cognome'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='comune_nascita',
            field=models.CharField(blank=True, help_text="Per chi è nato all'estero: la città estera.", max_length=120, verbose_name='comune di nascita'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='data_nascita',
            field=models.DateField(blank=True, null=True, verbose_name='data di nascita'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='nome'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='provincia_nascita',
            field=models.CharField(blank=True, help_text='Sigla della provincia (es. MB) oppure nazione estera: il modulo di cessione di fabbricato ha una casella sola per entrambi.', max_length=60, verbose_name='provincia o nazione estera di nascita'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='residenza_cap',
            field=models.CharField(blank=True, max_length=8, verbose_name='residenza: CAP'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='residenza_comune',
            field=models.CharField(blank=True, max_length=120, verbose_name='residenza: comune'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='residenza_provincia',
            field=models.CharField(blank=True, max_length=4, verbose_name='residenza: provincia'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='residenza_via',
            field=models.CharField(blank=True, max_length=160, verbose_name='residenza: via e numero civico'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='cittadinanza',
            field=models.CharField(blank=True, max_length=60, verbose_name='cittadinanza'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='cognome',
            field=models.CharField(blank=True, help_text='Separato dal nome perché i moduli ufficiali hanno due caselle distinte.', max_length=100, verbose_name='cognome'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='comune_nascita',
            field=models.CharField(blank=True, help_text="Per chi è nato all'estero: la città estera.", max_length=120, verbose_name='comune di nascita'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='data_nascita',
            field=models.DateField(blank=True, null=True, verbose_name='data di nascita'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='documento_autorita',
            field=models.CharField(blank=True, max_length=120, verbose_name='autorità che ha rilasciato il documento'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='documento_data_rilascio',
            field=models.DateField(blank=True, null=True, verbose_name='data di rilascio del documento'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='documento_numero',
            field=models.CharField(blank=True, max_length=40, verbose_name='numero del documento'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='documento_tipo',
            field=models.CharField(blank=True, choices=[('carta_identita', "Carta d'identità"), ('passaporto', 'Passaporto'), ('permesso_soggiorno', 'Permesso di soggiorno')], max_length=20, verbose_name='tipo di documento'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='nome'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='provincia_nascita',
            field=models.CharField(blank=True, help_text='Sigla della provincia (es. MB) oppure nazione estera: il modulo di cessione di fabbricato ha una casella sola per entrambi.', max_length=60, verbose_name='provincia o nazione estera di nascita'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='residenza_cap',
            field=models.CharField(blank=True, max_length=8, verbose_name='residenza: CAP'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='residenza_comune',
            field=models.CharField(blank=True, max_length=120, verbose_name='residenza: comune'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='residenza_provincia',
            field=models.CharField(blank=True, max_length=4, verbose_name='residenza: provincia'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='residenza_via',
            field=models.CharField(blank=True, max_length=160, verbose_name='residenza: via e numero civico'),
        ),
    ]
