# Generated by Django 6.0.4 on 2026-08-02 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_anagrafica_persone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='accessori',
            field=models.CharField(blank=True, max_length=60, verbose_name='accessori'),
        ),
        migrations.AddField(
            model_name='property',
            name='cap',
            field=models.CharField(blank=True, max_length=8, verbose_name='CAP'),
        ),
        migrations.AddField(
            model_name='property',
            name='civico',
            field=models.CharField(blank=True, max_length=16, verbose_name='numero civico'),
        ),
        migrations.AddField(
            model_name='property',
            name='comune',
            field=models.CharField(blank=True, max_length=120, verbose_name='comune'),
        ),
        migrations.AddField(
            model_name='property',
            name='ingressi',
            field=models.CharField(blank=True, max_length=60, verbose_name='ingressi'),
        ),
        migrations.AddField(
            model_name='property',
            name='interno',
            field=models.CharField(blank=True, max_length=16, verbose_name='interno'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_firmatario',
            field=models.ForeignKey(blank=True, help_text='Proprietario che firma la comunicazione di cessione di fabbricato: il modulo prevede un dichiarante solo. Cosa diversa da chi anticipa i costi di cessione.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties_firmatario', to='properties.ownerprofile', verbose_name='firma come cedente'),
        ),
        migrations.AddField(
            model_name='property',
            name='piano',
            field=models.CharField(blank=True, max_length=16, verbose_name='piano'),
        ),
        migrations.AddField(
            model_name='property',
            name='provincia',
            field=models.CharField(blank=True, max_length=4, verbose_name='provincia'),
        ),
        migrations.AddField(
            model_name='property',
            name='scala',
            field=models.CharField(blank=True, max_length=16, verbose_name='scala'),
        ),
        migrations.AddField(
            model_name='property',
            name='vani',
            field=models.CharField(blank=True, max_length=60, verbose_name='vani'),
        ),
        migrations.AddField(
            model_name='property',
            name='via',
            field=models.CharField(blank=True, max_length=160, verbose_name='via/piazza'),
        ),
        migrations.AlterField(
            model_name='property',
            name='indirizzo',
            field=models.CharField(blank=True, help_text='Testo libero mostrato nelle email e nella galleria pubblica.', max_length=255, verbose_name='indirizzo'),
        ),
    ]
