# Generated by Django 6.0.4 on 2026-08-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_property_indirizzo_strutturato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='codice_identificativo',
            field=models.CharField(blank=True, max_length=40, verbose_name='codice identificativo del contratto'),
        ),
        migrations.AddField(
            model_name='contract',
            name='data_registrazione',
            field=models.DateField(blank=True, null=True, verbose_name='data di registrazione'),
        ),
        migrations.AddField(
            model_name='contract',
            name='durata_rinnovo_anni',
            field=models.PositiveSmallIntegerField(default=2, help_text="Il '+2' della formula 4+2: 0 se il contratto non si rinnova.", verbose_name='rinnovo (anni)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='numero_registrazione',
            field=models.CharField(blank=True, max_length=30, verbose_name='numero di registrazione'),
        ),
        migrations.AddField(
            model_name='contract',
            name='serie_registrazione',
            field=models.CharField(blank=True, help_text='Es. 3T.', max_length=20, verbose_name='serie'),
        ),
        migrations.AddField(
            model_name='contract',
            name='ufficio_registrazione',
            field=models.CharField(blank=True, help_text="Ufficio dell'Agenzia delle Entrate (es. Desio).", max_length=120, verbose_name='ufficio territoriale di registrazione'),
        ),
    ]
