# Generated by Django 6.0.4 on 2026-08-02 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_contract_registrazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomassignment',
            name='subentra_a',
            field=models.ForeignKey(blank=True, help_text="Assegnazione dell'inquilino uscente a cui questa subentra. Non si deduce dalle date: fra l'uscita di uno e l'ingresso dell'altro può passare del tempo, e un atto legale non si fonda su un'euristica.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subentri', to='properties.roomassignment', verbose_name='subentra a'),
        ),
    ]
