# Generated by Django 6.0.4 on 2026-08-02 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_roomassignment_subentra_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('codice', models.CharField(choices=[('atto_subentro_locazione', 'Atto di subentro nel contratto'), ('cessione_fabbricato', 'Comunicazione di cessione di fabbricato')], max_length=40, verbose_name='documento')),
                ('nome', models.CharField(blank=True, help_text="Etichetta libera, es. 'Atto di subentro 2026'.", max_length=200, verbose_name='nome')),
                ('corpo_html', models.TextField(help_text="Documento HTML completo, CSS incluso, con segnaposto {{chiave}}. L'elenco dei segnaposto disponibili è quello del documento scelto.", verbose_name='corpo (HTML)')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='properties.property', verbose_name='immobile')),
            ],
            options={
                'verbose_name': 'modello documento',
                'verbose_name_plural': 'modelli documento',
                'ordering': ['property', 'codice'],
                'constraints': [models.UniqueConstraint(fields=('property', 'codice'), name='document_template_codice_unique_per_property')],
            },
        ),
    ]
