# Generated by Django 6.0.4 on 2026-08-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_documenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdocument',
            name='generato',
            field=models.BooleanField(default=False, help_text="Vero se il PDF l'ha prodotto l'applicazione. Solo questi vengono sostituiti quando si rigenera: la copia firmata e scansionata, caricata sotto lo stesso tipo, non si tocca.", verbose_name='generato dal sistema'),
        ),
        migrations.AlterField(
            model_name='tenantdocument',
            name='tipo',
            field=models.CharField(choices=[('carta_identita', "Carta d'identità"), ('codice_fiscale', 'Codice fiscale / Tessera sanitaria'), ('passaporto', 'Passaporto'), ('permesso_soggiorno', 'Permesso di soggiorno'), ('contratto_lavoro', 'Contratto di lavoro'), ('ricevuta_registrazione', 'Ricevuta di registrazione (agenzia)'), ('ricevuta_subentro', 'Ricevuta del subentro'), ('atto_subentro', 'Atto di subentro (utenze)'), ('atto_subentro_locazione', 'Atto di subentro nel contratto'), ('cessione_fabbricato', 'Comunicazione di cessione di fabbricato'), ('altro', 'Altro')], default='altro', max_length=30, verbose_name='tipo documento'),
        ),
    ]
