# Generated by Django 6.0.4 on 2026-08-03 12:26

from django.db import migrations, models


def fonde_ricevuta_subentro(apps, schema_editor):
    """``ricevuta_subentro`` era un doppione di ``ricevuta_registrazione``.

    Entrambi indicavano la ricevuta telematica dell'Agenzia: il subentro è un
    adempimento successivo sullo stesso contratto, non un documento diverso.
    """
    TenantDocument = apps.get_model("properties", "TenantDocument")
    TenantDocument.objects.filter(tipo="ricevuta_subentro").update(
        tipo="ricevuta_registrazione"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_documenti_generati'),
    ]

    operations = [
        # Prima i dati, poi il restringimento delle choices: al contrario
        # resterebbero righe con un tipo non più dichiarato.
        migrations.RunPython(fonde_ricevuta_subentro, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tenantdocument',
            name='tipo',
            field=models.CharField(choices=[('carta_identita', "Carta d'identità"), ('codice_fiscale', 'Codice fiscale / Tessera sanitaria'), ('passaporto', 'Passaporto'), ('permesso_soggiorno', 'Permesso di soggiorno'), ('contratto_lavoro', 'Contratto di lavoro'), ('ricevuta_registrazione', 'Registrazione contratto subentro'), ('atto_subentro', 'Atto di subentro (utenze)'), ('atto_subentro_locazione', 'Atto di subentro nel contratto'), ('cessione_fabbricato', 'Comunicazione di cessione di fabbricato'), ('altro', 'Altro')], default='altro', max_length=30, verbose_name='tipo documento'),
        ),
    ]
