# Generated by Django 6.0.4 on 2026-08-03 14:45

from django.db import migrations, models


ETICHETTA = "Atto di subentro (utenze)"


def declassa_atto_subentro(apps, schema_editor):
    """Il subentro delle utenze non è un documento dell'inquilino.

    I file già caricati non si buttano e non si spostano sull'immobile (altra
    tabella, altro percorso di storage): diventano documenti liberi, che il
    fascicolo elenca uno per uno sotto ``altri``. Il nome si conserva nella
    descrizione, altrimenti resterebbe un "Altro" senza storia.
    """
    TenantDocument = apps.get_model("properties", "TenantDocument")
    # La descrizione è già piena fino all'orlo del suo varchar: comporne una
    # più lunga farebbe fallire la migrazione in produzione, non qui.
    massimo = TenantDocument._meta.get_field("descrizione").max_length
    for documento in TenantDocument.objects.filter(tipo="atto_subentro"):
        documento.tipo = "altro"
        descrizione = (
            f"{ETICHETTA} · {documento.descrizione}"
            if documento.descrizione
            else ETICHETTA
        )
        documento.descrizione = descrizione[:massimo]
        documento.save(update_fields=["tipo", "descrizione"])


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_fonde_ricevuta_subentro'),
    ]

    operations = [
        migrations.RunPython(declassa_atto_subentro, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tenantdocument',
            name='tipo',
            field=models.CharField(choices=[('carta_identita', "Carta d'identità"), ('codice_fiscale', 'Codice fiscale / Tessera sanitaria'), ('passaporto', 'Passaporto'), ('permesso_soggiorno', 'Permesso di soggiorno'), ('contratto_lavoro', 'Contratto di lavoro'), ('ricevuta_registrazione', 'Registrazione contratto subentro'), ('atto_subentro_locazione', 'Atto di subentro nel contratto'), ('cessione_fabbricato', 'Comunicazione di cessione di fabbricato'), ('altro', 'Altro')], default='altro', max_length=30, verbose_name='tipo documento'),
        ),
    ]
