# Generated by Django 6.0.4 on 2026-08-06 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_toglie_atto_subentro_utenze'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomassignment',
            name='contract',
            field=models.ForeignKey(blank=True, help_text="Facoltativo: il contratto di locazione sotto cui sta questa occupazione. Serve a dire quali carte del contratto competono all'inquilino: senza contratto indicato, l'inquilino non vede i documenti collegati a un contratto.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='properties.contract', verbose_name='contratto'),
        ),
    ]
