# Generated by Django 6.0.4 on 2026-08-06 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_roomassignment_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocument',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Facoltativo: il contratto a cui il documento appartiene (firmato, side letter, ricevuta di registrazione). Se valorizzato e il documento è visibile agli inquilini, lo vedono solo quelli la cui occupazione sta sotto questo contratto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti', to='properties.contract', verbose_name='contratto'),
        ),
    ]
