# Generated by Django 6.0.4 on 2026-08-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0036_ownerbankaccount_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='tipo',
            field=models.CharField(choices=[('contratto', 'Contratto di locazione'), ('side_letter', 'Side letter'), ('registrazione_contratto', 'Registrazione contratto'), ('regolamento_condominiale', 'Regolamento condominiale'), ('regole_convivenza', 'Regole di convivenza'), ('altro', 'Altro')], default='altro', max_length=30, verbose_name='tipo documento'),
        ),
    ]
