# Generated by Django 6.0.4 on 2026-08-26 09:12

import django.db.models.deletion
import properties.models.share
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_alter_propertydocument_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocument',
            name='copia_di',
            field=models.ForeignKey(blank=True, help_text='Versione priva dei dati personali di terzi, da mandare a chi deve ancora firmare. Non compare fra i documenti ufficiali.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='copie_lettura', to='properties.propertydocument', verbose_name='copia per la lettura di'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='esponibile',
            field=models.BooleanField(default=False, help_text='Se attivo, il documento può essere messo in un link di lettura mandato a chi non ha un account. Una copia per la lettura nasce già spuntata; toglierla svuota i link già mandati.', verbose_name='esponibile in un link di lettura'),
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('token', models.CharField(default=properties.models.share.genera_token, editable=False, max_length=64, unique=True, verbose_name='token')),
                ('destinatario', models.CharField(help_text='A chi è indirizzato il link, es. «Simona Bagnato».', max_length=120, verbose_name='destinatario')),
                ('introduzione', models.TextField(blank=True, help_text='Due righe in cima alla pagina, prima delle voci.', verbose_name='introduzione')),
                ('attivo', models.BooleanField(default=True, help_text='Tolto, il link smette di funzionare (revoca).', verbose_name='attivo')),
                ('visite', models.PositiveIntegerField(default=0, verbose_name='aperture')),
                ('ultima_visita', models.DateTimeField(blank=True, null=True, verbose_name='ultima apertura')),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_documenti_creati', to=settings.AUTH_USER_MODEL, verbose_name='creato da')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_documenti', to='properties.property', verbose_name='immobile')),
                ('tenant', models.ForeignKey(blank=True, help_text='Facoltativo: se il destinatario è già in anagrafica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_documenti', to='properties.tenantprofile', verbose_name='inquilino')),
            ],
            options={
                'verbose_name': 'link di lettura',
                'verbose_name_plural': 'link di lettura',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='ordine')),
                ('titolo', models.CharField(blank=True, help_text='Vuoto: si usa il titolo del documento.', max_length=160, verbose_name='titolo')),
                ('corpo_md', models.TextField(blank=True, help_text='Chiarimento scritto a mano: quota condominio, utenze, scadenze.', verbose_name='testo (markdown)')),
                ('corpo_html', models.TextField(blank=True, editable=False)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voci_link', to='properties.propertydocument', verbose_name='documento')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci', to='properties.documentshare', verbose_name='link')),
            ],
            options={
                'verbose_name': 'voce del link',
                'verbose_name_plural': 'voci del link',
                'ordering': ['ordine', 'id'],
            },
        ),
    ]
