# Generated by Django 6.0.4 on 2026-08-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_alter_propertydocument_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentshare',
            name='introduzione_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='introduzione',
            field=models.TextField(blank=True, help_text="La spiegazione che apre la pagina, prima degli allegati: cosa si paga, come funzionano le utenze, cosa succede all'ingresso. Markdown, come i chiarimenti.", verbose_name='premessa (markdown)'),
        ),
    ]
