# Generated by Django 6.0.4 on 2026-08-26 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0040_documentshare_introduzione_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='copia_di',
            field=models.ForeignKey(blank=True, help_text='Versione priva dei dati personali di terzi, da mandare a chi deve ancora firmare. Non compare fra i documenti ufficiali.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='copie_lettura', to='properties.propertydocument', verbose_name='copia oscurata di'),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='esponibile',
            field=models.BooleanField(default=False, help_text='Se attivo, il documento può essere messo in un link di lettura mandato a chi non ha un account. Una copia oscurata nasce già spuntata; toglierla svuota i link già mandati.', verbose_name='esponibile in un link di lettura'),
        ),
    ]
