# Generated by Django 6.0.4 on 2026-09-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0041_alter_propertydocument_copia_di_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roomassignment',
            name='room_assignment_valid_to_after_valid_from',
        ),
        migrations.AddField(
            model_name='roomassignment',
            name='data_rinuncia',
            field=models.DateField(blank=True, help_text="Quando la rinuncia è stata comunicata. È un dato di cronaca: la fine occupazione viene posta uguale all'inizio, perché in stanza non ci si è mai entrati.", null=True, verbose_name='data della rinuncia'),
        ),
        migrations.AddField(
            model_name='roomassignment',
            name='rinunciata',
            field=models.BooleanField(default=False, help_text="L'occupazione non è mai iniziata: l'inquilino ha rinunciato prima di entrare. L'assegnazione resta perché tiene agganciato il deposito già versato, ma non produce alcun addebito (affitto, utenze, TARI, quota condominio) e non occupa la stanza.", verbose_name='rinuncia'),
        ),
        migrations.AddConstraint(
            model_name='roomassignment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), models.Q(('rinunciata', True), ('valid_to', models.F('valid_from'))), _connector='OR'), name='room_assignment_valid_to_after_valid_from'),
        ),
    ]
