# Generated by Django 6.0.4 on 2026-09-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0042_remove_roomassignment_room_assignment_valid_to_after_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='notifica_dichiarazioni',
            field=models.CharField(choices=[('tutti', 'Tutti i proprietari'), ('destinatario', 'Solo chi riceve il bonifico')], default='tutti', help_text="Chi riceve la notifica quando un inquilino dichiara di aver pagato dall'app. «Solo chi riceve il bonifico» ripiega su tutti se il conto di destinazione non è risolvibile.", max_length=20, verbose_name='avvisa del pagamento dichiarato'),
        ),
    ]
