# Generated by Django 6.0.4 on 2026-08-27 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0041_alter_propertydocument_copia_di_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aggiornato il')),
                ('post_id', models.CharField(help_text="Id Facebook del post: chiave naturale dell'upsert.", max_length=64, verbose_name='id del post')),
                ('group_id', models.CharField(blank=True, help_text="Gruppo in cui il post è stato trovato. Lo sa lo scraper (è il gruppo che sta scorrendo), non si ricava dal permalink: quello a volte manca. Serve quando i gruppi monitorati saranno più d'uno.", max_length=64, verbose_name='id del gruppo')),
                ('group_label', models.CharField(blank=True, max_length=120, verbose_name='nome del gruppo')),
                ('author_name', models.CharField(blank=True, max_length=200, verbose_name='autore')),
                ('author_url', models.URLField(blank=True, help_text='Usato anche dal bot per non ricontattare chi ripubblica.', max_length=500, verbose_name="profilo dell'autore")),
                ('permalink', models.URLField(blank=True, max_length=500, verbose_name='link al post')),
                ('link_messenger', models.URLField(blank=True, max_length=500, verbose_name='link a Messenger')),
                ('testo', models.TextField(blank=True, verbose_name='testo del post')),
                ('analisi', models.JSONField(blank=True, default=dict, help_text='Esito del classificatore: zona, budget_max, disponibile_da, stanze_compatibili (id di configurazione del bot, non Room), motivo.', verbose_name='analisi')),
                ('commento_proposto', models.TextField(blank=True, help_text='Testo da incollare sotto il post.', verbose_name='commento pubblico proposto')),
                ('privato_proposto', models.TextField(blank=True, help_text='Testo da incollare su Messenger.', verbose_name='messaggio privato proposto')),
                ('seen_at', models.DateTimeField(help_text='Quando il bot ha incontrato il post.', verbose_name='visto il')),
                ('stato', models.CharField(choices=[('nuovo', 'Da contattare'), ('contattato', 'Contattato'), ('risposto', 'Ha risposto'), ('scartato', 'Scartato')], default='nuovo', max_length=12, verbose_name='stato')),
                ('preso_at', models.DateTimeField(blank=True, null=True, verbose_name='preso in carico il')),
                ('contattato_at', models.DateTimeField(blank=True, null=True, verbose_name='contattato il')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('preso_da', models.ForeignKey(blank=True, help_text='Chi se ne occupa: evita che in due si scriva alla stessa persona.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_presi', to=settings.AUTH_USER_MODEL, verbose_name='preso in carico da')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='properties.property', verbose_name='immobile')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'lead',
                'ordering': ['-seen_at'],
                'indexes': [models.Index(fields=['property', 'stato'], name='leads_lead_propert_5683bc_idx'), models.Index(fields=['author_url'], name='leads_lead_author__507d16_idx')],
                'constraints': [models.UniqueConstraint(fields=('property', 'post_id'), name='lead_post_id_unique_per_property')],
            },
        ),
    ]
