# Generated by Django 6.0.4 on 2026-08-28 23:48

import leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='foto',
            field=models.TextField(blank=True, help_text='Ritaglio del profilo, incollato a mano per riconoscere la persona in mezzo agli annunci. Sta nella tabella e non su disco di proposito: la chiusura campagna cancella i lead in blocco, e un file su storage sopravviverebbe alla cancellazione promessa.', validators=[leads.models.valida_fotina], verbose_name='fotina'),
        ),
    ]
