# Generated by Django 6.0.4 on 2026-09-07 08:52

from django.conf import settings
from django.db import migrations, models


def segna_risposto_at(apps, schema_editor):
    """Chi era già «ha risposto» non ha una data: gli si dà l'ultimo
    aggiornamento, che è comunque quando qualcuno ha toccato lo stato.
    Senza, le statistiche non conterebbero le risposte già ricevute. E chi
    ha risposto è stato contattato: prima il salto diretto a «risposto» non
    marcava la data di contatto, e le percentuali verrebbero sopra il 100."""
    Lead = apps.get_model("leads", "Lead")
    for lead in Lead.objects.filter(stato="risposto", risposto_at__isnull=True):
        lead.risposto_at = lead.updated_at
        if lead.contattato_at is None:
            lead.contattato_at = lead.updated_at
        lead.save(update_fields=["risposto_at", "contattato_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_foto'),
        ('properties', '0042_remove_roomassignment_room_assignment_valid_to_after_valid_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lead',
            name='lead_post_id_unique_per_property',
        ),
        migrations.AddField(
            model_name='lead',
            name='canale',
            field=models.CharField(choices=[('fb_gruppo', 'Gruppo Facebook'), ('fb_post', 'Risposta a un mio post'), ('subito', 'Subito.it'), ('idealista', 'Idealista'), ('immobiliare', 'Immobiliare.it'), ('altro', 'Altro')], default='fb_gruppo', help_text='Da dove arriva il contatto. Il bot deposita solo dai gruppi Facebook; gli altri canali (annunci su Subito, Idealista, risposte a un post nostro) li inserisce a mano chi li riceve.', max_length=16, verbose_name='canale'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contatto',
            field=models.CharField(blank=True, help_text='Telefono, email o nome utente sulla piattaforma. Serve ai contatti inseriti a mano: per quelli del bot il recapito è Messenger.', max_length=200, verbose_name='contatto'),
        ),
        migrations.AddField(
            model_name='lead',
            name='risposto_at',
            field=models.DateTimeField(blank=True, help_text='Prima volta in cui è passato a «ha risposto». Resta anche se poi trova altro: le statistiche contano chi ha risposto, non chi sta rispondendo adesso.', null=True, verbose_name='ha risposto il'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='post_id',
            field=models.CharField(blank=True, help_text="Id Facebook del post: chiave naturale dell'upsert. Vuoto per i contatti inseriti a mano, che non hanno un post da cui ripartire.", max_length=64, verbose_name='id del post'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stato',
            field=models.CharField(choices=[('nuovo', 'Da contattare'), ('contattato', 'Contattato'), ('risposto', 'Ha risposto'), ('perso', 'Ha trovato altro'), ('scartato', 'Scartato')], default='nuovo', max_length=12, verbose_name='stato'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['property', 'canale'], name='leads_lead_propert_f6681c_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('post_id', ''), _negated=True), fields=('property', 'post_id'), name='lead_post_id_unique_per_property'),
        ),
        migrations.RunPython(segna_risposto_at, migrations.RunPython.noop),
    ]
